[log]
    # 日志输出文件
    file = "./log/gti.log"
    # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    level = "info"
    # 日志输出格式，可选：text | json
    format = "text"
    # 是否输出到终端
    stdout = true
    # 时间格式，标准库时间格式
    timeFormat = "2006/01/02 15:04:05.000000"
    # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    stackLevel = "error"
    # 文件最大留存时间，d:天、h:时、m:分、s:秒
    fileMaxAge = "7d"
    # 文件最大尺寸限制，单位（MB）
    fileMaxSize = 100
    # 文件切割方式
    fileCutRule = "day"
    # 是否启用调用文件全路径
    callerFullPath = true
    # 是否启用分级存储
    classifiedStorage = true
[redis]
    # 客户端连接地址
    addrs = ["127.0.0.1:6379"]
    # 数据库号
    db = 0
    # 用户名
    username = ""
    # 密码
    password = ""
    # 最大重试次数
    maxRetries = 3
    # key前缀
    prefix = "gti"
[mongo]
    # 数据源
    dsn = "mongodb://root:12345678@127.0.0.1:27017"
    # 数据库
    database = "mahjong"
[jwt]
    # jwt发行方
    issuer = "mahjong"
    # 过期时间
    expiredTime = 7200
    # 秘钥KEY
    secretKey = "MZlD9KpffCPh7oJtCaDoqFQE1cqZyVKfoxeQdYy4mkYKkBUCQQDQpPO7MmTPmuLI"
    # 身份认证KEY
    identityKey = "uid"